# Generated by Django 2.0.4 on 2018-12-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='活动日期')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('remark', models.TextField(blank=True, max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'DOS活动',
                'verbose_name_plural': 'DOS活动',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.TextField(max_length=600, verbose_name='演讲素材')),
            ],
            options={
                'verbose_name': '演讲素材（论据）',
                'verbose_name_plural': '演讲素材（论据）',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='书籍名称')),
                ('mappingnote', models.ImageField(blank=True, null=True, upload_to='MappingNote', verbose_name='脑图笔记')),
                ('author', models.CharField(blank=True, max_length=20, null=True, verbose_name='书籍作者')),
                ('bookcover', models.ImageField(blank=True, null=True, upload_to='bookcover', verbose_name='书籍封面')),
                ('bookreview', models.TextField(blank=True, max_length=600, null=True, verbose_name='推荐词/书评')),
                ('note', models.TextField(blank=True, max_length=600, null=True, verbose_name='读书笔记')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='相关网址')),
                ('application', models.CharField(blank=True, max_length=100, null=True, verbose_name='适合人群')),
                ('tag', models.TextField(blank=True, max_length=20, null=True, verbose_name='标签')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '好书',
                'verbose_name_plural': '好书',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='俱乐部名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club', verbose_name='俱乐部logo')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='官网网址')),
            ],
            options={
                'verbose_name': 'DOS俱乐部',
                'verbose_name_plural': 'DOS俱乐部',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(verbose_name='课程编号')),
                ('partid', models.IntegerField(verbose_name='小节编号')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('lr', models.BooleanField(default=True, verbose_name='靠左')),
                ('content', models.TextField(max_length=200, verbose_name='发言内容')),
                ('translate', models.TextField(max_length=100, verbose_name='翻译')),
            ],
            options={
                'verbose_name': '英语对话',
                'verbose_name_plural': '英语对话',
                'ordering': ['-courseid'],
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mydate', models.DateField(unique=True, verbose_name='日期')),
                ('getuptime', models.TextField(max_length=10, verbose_name='起床时间')),
                ('production', models.TextField(max_length=100, verbose_name='成就作品')),
                ('work', models.TextField(max_length=100, verbose_name='工作内容')),
                ('study', models.TextField(max_length=100, verbose_name='学习内容')),
                ('socialTask', models.TextField(max_length=100, verbose_name='社群运营')),
                ('happy', models.TextField(max_length=100, verbose_name='开心乐事')),
                ('help', models.TextField(max_length=100, verbose_name='助人为乐')),
                ('read', models.TextField(max_length=100, verbose_name='阅读好书')),
                ('activity', models.TextField(max_length=100, verbose_name='参加活动')),
                ('newFriend', models.TextField(max_length=100, verbose_name='认识新朋友')),
                ('oldFriend', models.TextField(max_length=100, verbose_name='再会老朋友')),
                ('cost', models.IntegerField(default=0, verbose_name='消费金额')),
                ('remark', models.TextField(max_length=100, verbose_name='备忘记录')),
                ('sleeptime', models.TextField(max_length=10, verbose_name='休息时间')),
                ('goal', models.TextField(max_length=100, verbose_name='明日目标')),
                ('todo', models.TextField(max_length=100, verbose_name='重要待办')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
                'ordering': ['-mydate'],
            },
        ),
        migrations.CreateModel(
            name='DreamMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name='作者编号')),
                ('type', models.TextField(max_length=6, verbose_name='类型')),
                ('dream', models.TextField(max_length=400, verbose_name='梦想')),
                ('state', models.TextField(max_length=200, verbose_name='现状')),
                ('rate', models.TextField(default=0, max_length=6, verbose_name='圆梦进度')),
            ],
            options={
                'verbose_name': '梦想进度表',
                'verbose_name_plural': '梦想进度表',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='演讲标题')),
                ('draft', models.TextField(max_length=6000, verbose_name='演讲稿')),
                ('video', models.URLField(verbose_name='演讲视频链接')),
            ],
            options={
                'verbose_name': '演讲范例',
                'verbose_name_plural': '演讲范例',
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='头像')),
                ('color', models.CharField(max_length=10, verbose_name='颜色')),
            ],
            options={
                'verbose_name': '虚拟人物',
                'verbose_name_plural': '虚拟人物',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name='作者编号')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('goal', models.TextField(max_length=60, verbose_name='目标')),
                ('done', models.BooleanField(verbose_name='是否完成')),
                ('top', models.BooleanField(default=False, verbose_name='是否置顶')),
            ],
            options={
                'verbose_name': '目标清单',
                'verbose_name_plural': '目标清单',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(blank=True, null=True, verbose_name='上传人编号')),
                ('cid', models.IntegerField(blank=True, null=True, verbose_name='课程编号')),
                ('sid', models.IntegerField(blank=True, null=True, verbose_name='分享编号')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='配图')),
            ],
        ),
        migrations.CreateModel(
            name='ITnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容')),
                ('code', models.TextField(blank=True, max_length=1000, null=True, verbose_name='代码')),
                ('url', models.URLField(blank=True, null=True, verbose_name='参考链接')),
                ('img', models.ImageField(blank=True, null=True, upload_to='noteimg', verbose_name='配图')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': 'DOS编程笔记',
                'verbose_name_plural': 'DOS编程笔记',
                'ordering': ['-pubtime'],
            },
        ),
        migrations.CreateModel(
            name='ITnoteindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('index', models.CharField(blank=True, max_length=200, null=True, verbose_name='索引值')),
            ],
            options={
                'verbose_name': 'DOS编程笔记-索引',
                'verbose_name_plural': 'DOS编程笔记-索引',
            },
        ),
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=20, verbose_name='语言')),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
            },
        ),
        migrations.CreateModel(
            name='LifeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name='作者编号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '人生大事记',
                'verbose_name_plural': '人生大事记',
            },
        ),
        migrations.CreateModel(
            name='MiniDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name='作者编号')),
                ('date', models.DateField(verbose_name='日期')),
                ('item', models.TextField(max_length=60, verbose_name='日记事项')),
                ('done', models.BooleanField(verbose_name='是否完成')),
            ],
            options={
                'verbose_name': '微日记',
                'verbose_name_plural': '微日记',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=100, verbose_name='演讲观点')),
            ],
            options={
                'verbose_name': '演讲观点（论点）',
                'verbose_name_plural': '演讲观点（论点）',
            },
        ),
        migrations.CreateModel(
            name='QPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonNo', models.IntegerField(default=0, verbose_name='季编号')),
                ('date', models.DateField(verbose_name='日期')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
                ('topic', models.CharField(max_length=100, verbose_name='辩题')),
                ('iqyurl', models.URLField(max_length=100, verbose_name='爱奇艺视频链接')),
                ('url', models.URLField(verbose_name='视频链接')),
                ('note', models.TextField(default='——帮你圆梦的DOS大学校长-朝阳整理13908056224', max_length=1000, verbose_name='笔记')),
                ('ifwatched', models.BooleanField(default=False, verbose_name='是否看过')),
            ],
            options={
                'verbose_name': 'DOS奇葩说',
                'verbose_name_plural': 'DOS奇葩说',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=100, verbose_name='金句')),
            ],
            options={
                'verbose_name': '演讲金句',
                'verbose_name_plural': '演讲金句',
            },
        ),
        migrations.CreateModel(
            name='share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name='作者编号')),
                ('nickName', models.TextField(max_length=20, verbose_name='微信昵称')),
                ('avatarUrl', models.URLField(verbose_name='微信头像')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('type', models.TextField(max_length=8, verbose_name='类型')),
                ('title', models.TextField(max_length=60, verbose_name='标题')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('imglist', models.TextField(default='', max_length=1000, verbose_name='配图')),
                ('tag', models.TextField(max_length=20, verbose_name='标签')),
                ('favnum', models.IntegerField(default=0, verbose_name='点赞数')),
                ('favlist', models.TextField(default='', max_length=100, verbose_name='收藏人列表')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
            },
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='费用')),
                ('ifsignin', models.BooleanField(default=False, verbose_name='是否参与')),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.Activity', verbose_name='活动名称')),
            ],
            options={
                'verbose_name': 'DOS签到表',
                'verbose_name_plural': 'DOS签到表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(blank=True, null=True, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='学员昵称')),
                ('wx', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信号')),
                ('isVIP', models.BooleanField(default=False, verbose_name='是否是校友')),
            ],
            options={
                'verbose_name': 'DOS学员',
                'verbose_name_plural': 'DOS学员',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, verbose_name='演讲主题')),
            ],
            options={
                'verbose_name': '演讲主题',
                'verbose_name_plural': '演讲主题',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('img', models.ImageField(blank=True, null=True, upload_to='vipimg', verbose_name='配图')),
                ('price', models.IntegerField(verbose_name='市场价')),
                ('pay', models.IntegerField(verbose_name='实购价')),
                ('key', models.TextField(blank=True, max_length=400, null=True, verbose_name='领取方式')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='笔记')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('indate', models.DateTimeField(blank=True, null=True, verbose_name='有效期')),
            ],
            options={
                'verbose_name': 'DOS校友福利',
                'verbose_name_plural': 'DOS校友福利',
                'ordering': ['-pubtime'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(verbose_name='课程编号')),
                ('partid', models.IntegerField(verbose_name='小节编号')),
                ('word', models.CharField(max_length=20, verbose_name='单词')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
            },
        ),
        migrations.AddField(
            model_name='signin',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_name', to='dos.Student', verbose_name='参与学员'),
        ),
        migrations.AddField(
            model_name='quote',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.Topic', verbose_name='演讲主题'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.Topic', verbose_name='演讲主题'),
        ),
        migrations.AddField(
            model_name='itnote',
            name='lan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dos.Lan', verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='example',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.Topic', verbose_name='演讲主题'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='spokesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.Figure', verbose_name='发言人'),
        ),
        migrations.AddField(
            model_name='argument',
            name='O_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dos.Opinion', verbose_name='演讲论点'),
        ),
    ]
