# Generated by Django 2.0.4 on 2018-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='tag',
            field=models.CharField(default='技能', max_length=50, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='pay',
            field=models.IntegerField(default=0, verbose_name='实购价'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='price',
            field=models.IntegerField(default=0, verbose_name='市场价'),
        ),
    ]
